### ISSUE TITLE
Problem not finding "import mldatasets" in python code

### ISSUE THREAD

**Issue by choi-yongsuk** [PacktPublishing/Interpretable-Machine-Learning-with-Python-2E#1]
After completing the installation by executing the "pip install machine-learning-datasets" command, and executing the "import mldatasets" code in the python code, the error "ModuleNotFoundError: No module named 'mldatasets' " occurred. 

<img width="1072" alt="image" src="https://github.com/PacktPublishing/Interpretable-Machine-Learning-with-Python-2E/assets/36021025/864daf0a-8377-472c-bc10-2c6362d5f89b">

And I solved it by checking and modifying the code as shown below.

`import machine_learning_datasets as mldatasets`

I think you need to edit the code of each chapter or the name of the lib.

**Comment by smasis001** [comment]
Thank you for alerting me of this oversight. New commit #[ab90888](https://github.com/PacktPublishing/Interpretable-Machine-Learning-with-Python-2E/commit/ab908884b05503182f80ca0ac319c3b84bdd5985) resolved this issue.
